---
- src: https://github.com/diranetafen/ansible-role-containerized-wordpress.git
#- src: https://github.com/iMartzen/ansible-role-centos-docker-compose-setup.git
#- src: https://github.com/madjouroot/ansible-role-centos-docker-compose-setup.git 
